### ISSUE TITLE
Certificate Issue - Site Not Secure Warning

### ISSUE THREAD

**Issue by esa1975** [linuxappstore/linuxappstore#47]
I noticed that the site was down yesterday, possibly longer and now when I load the page I am getting a security warning. You may already be aware but I wanted to call it to your attention in case you weren't. Thanks for the great tool. I use it quite a bit

**Comment by chadalen** [comment]
@esa1975 I have decided to end the project.

**Comment by esa1975** [comment]
> @esa1975 I have decided to end the project.

Understood. Sorry to hear that but happy that I got to use it while it was available. I think it filled a need so maybe someone else will pick it up. Thanks for the effort and best of luck in the future.
